[package]
name = "poseidon2"
version = "0.1.0"
edition = "2021"
type = "bin"

[dependencies]
boojum = { path = "../zksync-crypto/crates/boojum" }
serde_json = "1.0"
chrono = "0.4"
ark-std = { version = "0.3", features = ["print-trace"] }
